[project]
name = 'Autonomous-Journalism-and-Fact-Checking'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.fact-check]
path = 'contracts/fact-check.clar'
clarity_version = 2
epoch = 2.5

[contracts.news-article]
path = 'contracts/news-article.clar'
clarity_version = 2
epoch = 2.5

[contracts.staking]
path = 'contracts/staking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
